<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>net.shibboleth</groupId>
        <artifactId>parent</artifactId>
        <version>17.0.2</version>
    </parent>

    <name>Shibboleth IdP :: Plugins :: Esup-Otp Login Flow</name>
    <description>An IdP plugin providing Esup-Otp login support.</description>
    <groupId>fr.renater.shibboleth.esup.otp</groupId>
    <artifactId>idp-plugin-esup-otp-parent</artifactId>
    <version>1.0.2</version>
    <packaging>pom</packaging>
    
    <properties>
        <shibboleth.projectName>java-idp-plugin-esup-otp</shibboleth.projectName>
        <idp.groupId>net.shibboleth.idp</idp.groupId>
        <idp.version>5.1.0</idp.version>
        <opensaml.version>5.1.0</opensaml.version>
        <shib-shared.version>9.1.0</shib-shared.version>
        <checkstyle.configLocation>${project.basedir}/resources/checkstyle/checkstyle.xml</checkstyle.configLocation>
        <lombok.version>1.18.36</lombok.version>
    </properties>

    <dependencies>
        <!-- Compile Dependencies -->

        <!-- Provided Dependencies -->

        <!-- Runtime Dependencies -->

        <!-- Test Dependencies -->
        
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>${slf4j.groupId}</groupId>
            <artifactId>slf4j-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Managed Dependencies -->
    </dependencies>
    
    <dependencyManagement>
        <dependencies>
            <!-- Esup Otp client dependency -->
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>esup-otp-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>esup-otp-impl</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- IdP BOM when importing IdP dependencies -->
            <dependency>
                <groupId>net.shibboleth.idp</groupId>
                <artifactId>idp-bom</artifactId>
                <version>${idp.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>net.shibboleth</groupId>
                <artifactId>shib-profile-bom</artifactId>
                <version>${idp.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>net.shibboleth</groupId>
                <artifactId>shib-attribute-bom</artifactId>
                <version>${idp.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.opensaml</groupId>
                <artifactId>opensaml-bom</artifactId>
                <version>${opensaml.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>net.shibboleth</groupId>
                <artifactId>shib-shared-bom</artifactId>
                <version>${shib-shared.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <index>true</index>
                        <manifestEntries>
                            <Automatic-Module-Name>${automatic.module.name}</Automatic-Module-Name>
                            <Implementation-Title>${project.artifactId}</Implementation-Title>
                            <Implementation-Version>${project.version}</Implementation-Version>
                            <Sealed>false</Sealed>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <modules>
        <module>esup-otp-impl</module>
        <module>esup-otp-api</module>
        <!-- All DIST modules must come after the -api and -impl modules -->
        <module>esup-otp-dist</module>
    </modules>
    
</project>
